export enum ActionType {
  LOGIN_START = 'LOGIN_START',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGIN_USER = 'LOGIN_USER',
  LOGOUT_USER = 'LOGOUT_USER',
  REFRESH_USER_START = 'REFRESH_USER_START',
  REFRESH_USER = 'REFRESH_USER',
  REFRESH_USER_FAILED = 'REFRESH_USER_FAILED',
  CLEAR_ERROR = 'CLEAR_ERROR',
}
